export const quizActionTypes = {
	SET_LOADING_ERROR: "SET_LOADING_ERROR",
	SET_QUESTION_DATA: "SET_QUESTION_DATA",
	RESET_QUIZ_STATE: "RESET_QUIZ_STATE",
	SET_SELECTED_OPTION: "SET_SELECTED_OPTION",
	CHANGE_QUESTION_NUMBER: "CHANGE_QUESTION_NUMBER",
	SET_SCORE: "SET_SCORE",
};
